spring:
  profiles:
    include: oauth


  datasource:
    driverClassName: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://svc.sel4.cloudtype.app:30934/server
    username: root
    password: 1234
  jpa:
    database-platform: org.hibernate.dialect.MariaDBDialect
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
logging:
  level:
    org:
      springframework:
        orm:
          jpa: DEBUG
server:
  servlet:
    encoding:
      force-response: true
cloud:
  aws:
    s3:
      bucket: my-github-actions-s3-burket
    credentials:
      access-key: AKIATYK3GYSCFHHJCTAY
      secret-key: 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
    region:
      static: ap-northeast-2
      auto: false
    stack:
      auto: false
jwt:
  temporary-token-expiration-ms: 1800000
  secret: woduddl13@@